'use client';

import React from 'react';
import { ModalSection } from '@/components/ui/Modal';
import { BasicInfoSectionProps } from '../types';

export function BasicInfoSection({
  formData,
  setFormData,
  t,
  nameInputRef,
  slugModified,
  setSlugModified,
  currentDomain,
  generateSlug,
}: BasicInfoSectionProps) {
  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;

    if (name === 'name' && !slugModified) {
      setFormData(prev => ({
        ...prev,
        [name]: value,
        slug: generateSlug(value)
      }));
    } else if (name === 'slug') {
      setSlugModified(true);
      setFormData(prev => ({
        ...prev,
        [name]: generateSlug(value)
      }));
    } else {
      setFormData(prev => ({
        ...prev,
        [name]: value
      }));
    }
  };

  return (
    <ModalSection title={t('basicInformation')}>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label htmlFor="name" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            {t('productName')}
          </label>
          <input
            type="text"
            id="name"
            name="name"
            value={formData.name}
            onChange={handleInputChange}
            ref={nameInputRef}
            className="w-full px-3 py-2.5 border border-gray-300 dark:border-gray-600 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-gray-700 dark:text-white"
            placeholder={t('enterProductName')}
            required
          />
        </div>

        <div>
          <label htmlFor="slug" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            {t('urlSlug')}
            <span className="text-xs text-gray-500 dark:text-gray-400 ml-1">({t('autoGenerated')})</span>
          </label>
          <div className="relative">
            <input
              type="text"
              id="slug"
              name="slug"
              value={formData.slug}
              onChange={handleInputChange}
              className="w-full px-3 py-2.5 border border-gray-300 dark:border-gray-600 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-gray-700 dark:text-white pr-12"
              placeholder="product-url-slug"
              required
            />
            {!slugModified && (
              <span className="absolute right-3 top-1/2 transform -translate-y-1/2 text-xs text-blue-600 dark:text-blue-400 bg-blue-100 dark:bg-blue-900/30 rounded px-2 py-1">
                Auto
              </span>
            )}
          </div>
          <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">
            {currentDomain ? `${currentDomain}/p/` : 'https://example.com/p/'}<strong>{formData.slug || 'product-slug'}</strong>
          </p>
        </div>
      </div>

      <div>
        <label htmlFor="description" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
          Description
        </label>
        <textarea
          id="description"
          name="description"
          value={formData.description || ''}
          onChange={handleInputChange}
          rows={3}
          className="w-full px-3 py-2.5 border border-gray-300 dark:border-gray-600 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-gray-700 dark:text-white"
          placeholder="Describe your product"
          required
        />
      </div>

      <div>
        <label htmlFor="long_description" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
          Detailed Description (Markdown)
          <span className="text-xs text-gray-500 dark:text-gray-400 ml-1">(Optional - for checkout page)</span>
        </label>
        <textarea
          id="long_description"
          name="long_description"
          value={formData.long_description || ''}
          onChange={handleInputChange}
          rows={8}
          className="w-full px-3 py-2.5 border border-gray-300 dark:border-gray-600 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-gray-700 dark:text-white font-mono text-sm"
          placeholder="## What's included?&#10;&#10;- Feature 1&#10;- Feature 2&#10;&#10;### Why choose this?&#10;&#10;Because it's **awesome**!"
        />
        <p className="mt-2 text-xs text-gray-500 dark:text-gray-400 flex items-start gap-1">
          <span>💡</span>
          <span>Tip: If you don&apos;t know Markdown syntax, ask any AI to create formatted content for you</span>
        </p>
      </div>
    </ModalSection>
  );
}
