#!/usr/bin/env bun
/**
 * GateFlow Supabase Setup Tool
 *
 * Automatically fetches Supabase API keys and generates .env.local
 *
 * Usage:
 *   bun run scripts/setup-supabase.ts
 *
 * Requirements:
 *   - Supabase Personal Access Token (from https://supabase.com/dashboard/account/tokens)
 */

import { createInterface } from 'readline';
import { writeFileSync, existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { exec } from 'child_process';

const SUPABASE_API = 'https://api.supabase.com/v1';

interface Project {
  id: string;
  name: string;
  organization_id: string;
  region: string;
  created_at: string;
}

interface ApiKey {
  name: string;
  api_key: string;
}

const rl = createInterface({
  input: process.stdin,
  output: process.stdout,
});

function prompt(question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer.trim());
    });
  });
}

function openBrowser(url: string) {
  const platform = process.platform;
  let command: string;

  switch (platform) {
    case 'darwin': // macOS
      command = `open "${url}"`;
      break;
    case 'win32': // Windows
      command = `start "" "${url}"`;
      break;
    default: // Linux
      command = `xdg-open "${url}"`;
  }

  exec(command, (error) => {
    if (error) {
      console.log(`   Could not open browser automatically.`);
      console.log(`   Please open manually: ${url}\n`);
    }
  });
}

async function fetchWithAuth(url: string, token: string) {
  const response = await fetch(url, {
    headers: {
      'Authorization': `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`API Error (${response.status}): ${error}`);
  }

  return response.json();
}

async function getProjects(token: string): Promise<Project[]> {
  return fetchWithAuth(`${SUPABASE_API}/projects`, token);
}

async function getApiKeys(token: string, projectRef: string): Promise<ApiKey[]> {
  return fetchWithAuth(`${SUPABASE_API}/projects/${projectRef}/api-keys`, token);
}

async function getProjectDetails(token: string, projectRef: string): Promise<{ endpoint: string }> {
  const project = await fetchWithAuth(`${SUPABASE_API}/projects/${projectRef}`, token);
  // Supabase URL format: https://{ref}.supabase.co
  return {
    endpoint: `https://${projectRef}.supabase.co`
  };
}

function generateEnvContent(
  supabaseUrl: string,
  anonKey: string,
  serviceRoleKey: string,
  existingEnv?: string
): string {
  const supabaseBlock = `# ===========================================
# SUPABASE (auto-generated by setup-supabase.ts)
# ===========================================
NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${anonKey}
SUPABASE_SERVICE_ROLE_KEY=${serviceRoleKey}
`;

  if (existingEnv) {
    // Remove existing Supabase config if present
    const cleanedEnv = existingEnv
      .replace(/# =+\n# SUPABASE.*?\n# =+\n(.*?\n)*?(?=# =|$)/gs, '')
      .replace(/NEXT_PUBLIC_SUPABASE_URL=.*\n?/g, '')
      .replace(/NEXT_PUBLIC_SUPABASE_ANON_KEY=.*\n?/g, '')
      .replace(/SUPABASE_SERVICE_ROLE_KEY=.*\n?/g, '')
      .trim();

    return supabaseBlock + '\n' + cleanedEnv;
  }

  return supabaseBlock + `
# ===========================================
# STRIPE (configure in admin panel or here)
# ===========================================
# NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_...
# STRIPE_SECRET_KEY=sk_test_...
# STRIPE_WEBHOOK_SECRET=whsec_...

# ===========================================
# SITE URLS
# ===========================================
NEXT_PUBLIC_SITE_URL=http://localhost:3000
NEXT_PUBLIC_BASE_URL=http://localhost:3000
# MAIN_DOMAIN=example.com

# ===========================================
# PRODUCTION
# ===========================================
NODE_ENV=development
PORT=3000
`;
}

async function main() {
  console.log(`
╔═══════════════════════════════════════════════════════════╗
║         GateFlow Supabase Setup Tool                      ║
║                                                           ║
║  This tool will automatically fetch your Supabase         ║
║  API keys and generate .env.local                         ║
╚═══════════════════════════════════════════════════════════╝
`);

  // Step 1: Get Personal Access Token
  let token = process.env.SUPABASE_ACCESS_TOKEN;

  if (token) {
    console.log('Step 1: Personal Access Token\n');
    console.log('   ✓ Using SUPABASE_ACCESS_TOKEN from environment\n');
  } else {
    console.log('Step 1: Personal Access Token\n');

    const tokenUrl = 'https://supabase.com/dashboard/account/tokens';
    console.log(`   Opening: ${tokenUrl}\n`);
    openBrowser(tokenUrl);

    console.log('   1. Click "Generate new token"');
    console.log('   2. Name it "GateFlow Setup"');
    console.log('   3. Copy the token\n');

    token = await prompt('Paste your Personal Access Token: ');

    if (!token) {
      console.error('❌ Token is required');
      process.exit(1);
    }
  }

  // Step 2: Fetch projects
  console.log('\n⏳ Fetching your projects...\n');

  let projects: Project[];
  try {
    projects = await getProjects(token);
  } catch (error) {
    console.error('❌ Failed to fetch projects. Is your token valid?');
    console.error((error as Error).message);
    process.exit(1);
  }

  if (projects.length === 0) {
    console.error('❌ No projects found. Create a project at https://supabase.com/dashboard');
    process.exit(1);
  }

  // Step 3: Select project
  console.log('Step 2: Select Project\n');
  projects.forEach((p, i) => {
    console.log(`   [${i + 1}] ${p.name} (${p.id}) - ${p.region}`);
  });
  console.log('');

  const selection = await prompt(`Select project (1-${projects.length}): `);
  const projectIndex = parseInt(selection, 10) - 1;

  if (isNaN(projectIndex) || projectIndex < 0 || projectIndex >= projects.length) {
    console.error('❌ Invalid selection');
    process.exit(1);
  }

  const selectedProject = projects[projectIndex];
  console.log(`\n✓ Selected: ${selectedProject.name}\n`);

  // Step 4: Fetch API keys
  console.log('⏳ Fetching API keys...\n');

  let apiKeys: ApiKey[];
  try {
    apiKeys = await getApiKeys(token, selectedProject.id);
  } catch (error) {
    console.error('❌ Failed to fetch API keys');
    console.error((error as Error).message);
    process.exit(1);
  }

  const anonKey = apiKeys.find(k => k.name === 'anon')?.api_key;
  const serviceRoleKey = apiKeys.find(k => k.name === 'service_role')?.api_key;

  if (!anonKey || !serviceRoleKey) {
    // Try new key format
    const publishableKey = apiKeys.find(k => k.name.includes('publishable'))?.api_key;
    const secretKey = apiKeys.find(k => k.name.includes('secret'))?.api_key;

    if (!publishableKey || !secretKey) {
      console.error('❌ Could not find API keys. Available keys:', apiKeys.map(k => k.name));
      process.exit(1);
    }
  }

  const supabaseUrl = `https://${selectedProject.id}.supabase.co`;

  // Step 5: Generate .env.local
  console.log('Step 3: Generate Configuration\n');

  const envPath = join(process.cwd(), 'admin-panel', '.env.local');
  const envExamplePath = join(process.cwd(), 'admin-panel', '.env.example');

  let existingEnv: string | undefined;
  if (existsSync(envPath)) {
    existingEnv = readFileSync(envPath, 'utf-8');
    console.log('   ⚠️  .env.local already exists - will merge\n');
  } else if (existsSync(envExamplePath)) {
    existingEnv = readFileSync(envExamplePath, 'utf-8');
  }

  const envContent = generateEnvContent(
    supabaseUrl,
    anonKey!,
    serviceRoleKey!,
    existingEnv
  );

  // Preview
  console.log('   Preview of Supabase configuration:');
  console.log('   ─────────────────────────────────────');
  console.log(`   NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}`);
  console.log(`   NEXT_PUBLIC_SUPABASE_ANON_KEY=${anonKey!.substring(0, 20)}...`);
  console.log(`   SUPABASE_SERVICE_ROLE_KEY=${serviceRoleKey!.substring(0, 20)}...`);
  console.log('');

  const confirm = await prompt('Write to .env.local? (y/n): ');

  if (confirm.toLowerCase() !== 'y') {
    console.log('\n❌ Cancelled');
    process.exit(0);
  }

  writeFileSync(envPath, envContent);
  console.log(`\n✅ Configuration saved to ${envPath}`);

  // Summary
  console.log(`
╔═══════════════════════════════════════════════════════════╗
║                     Setup Complete!                        ║
╚═══════════════════════════════════════════════════════════╝

Next steps:

1. Run migrations in Supabase Dashboard:
   https://supabase.com/dashboard/project/${selectedProject.id}/sql

   Execute all files from: supabase/migrations/

2. Configure SMTP (for magic links):
   https://supabase.com/dashboard/project/${selectedProject.id}/auth/providers

3. Start the app:
   cd admin-panel && bun run dev

4. First user to register becomes admin!
`);

  rl.close();
}

main().catch((error) => {
  console.error('Fatal error:', error);
  process.exit(1);
});
