-- Create main database structure for GateFlow Admin Panel
-- Migration: 20250709160000_initial_schema
-- Based on existing gateflow_setup.sql and user_product_access_setup.sql

BEGIN;

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create products table (compatible with existing gatekeeper system)
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL, -- Required for gatekeeper system
  description TEXT,
  icon TEXT, -- Used by gatekeeper for UI
  price NUMERIC DEFAULT 0 NOT NULL,
  theme TEXT DEFAULT 'dark' NOT NULL, -- Used by gatekeeper for theming
  layout_template TEXT DEFAULT 'default' NOT NULL, -- Used by gatekeeper layouts
  stripe_price_id TEXT, -- Stripe integration
  is_active BOOLEAN NOT NULL DEFAULT true, -- Admin panel functionality
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Create user_product_access table (compatible with existing gatekeeper system)
CREATE TABLE IF NOT EXISTS user_product_access (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  product_slug TEXT REFERENCES products(slug) ON DELETE CASCADE NOT NULL, -- Uses slug for gatekeeper compatibility
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  UNIQUE (user_id, product_slug) -- Ensure a user can only have one access entry per product
);

-- Create audit_logs table for tracking admin actions
CREATE TABLE IF NOT EXISTS audit_logs (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  action TEXT NOT NULL,
  user_id UUID NOT NULL,
  details JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_products_slug ON products(slug);
CREATE INDEX IF NOT EXISTS idx_products_is_active ON products(is_active);
CREATE INDEX IF NOT EXISTS idx_products_price ON products(price);
CREATE INDEX IF NOT EXISTS idx_products_created_at ON products(created_at);
CREATE INDEX IF NOT EXISTS idx_user_product_access_user_id ON user_product_access(user_id);
CREATE INDEX IF NOT EXISTS idx_user_product_access_product_slug ON user_product_access(product_slug);
CREATE INDEX IF NOT EXISTS idx_user_product_access_unique ON user_product_access(user_id, product_slug);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at);

-- Enable Row Level Security
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_product_access ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- RLS Policies for products table (compatible with gatekeeper system)
-- Allow public read access for all products (needed by gatekeeper.js)
CREATE POLICY "Allow public read access for everyone" ON products
  FOR SELECT
  USING (true);

-- Allow authenticated users full access to products (admin panel)
CREATE POLICY "Allow authenticated users to manage products" ON products
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- RLS Policies for user_product_access table (compatible with gatekeeper system)
-- Allow users to read their own access records
CREATE POLICY "Allow users to read their own product access" ON user_product_access
  FOR SELECT
  USING (auth.uid() = user_id);

-- Allow service role to insert access records (used by Edge Functions and admin panel)
CREATE POLICY "Allow service role to insert product access" ON user_product_access
  FOR INSERT
  WITH CHECK (true);

-- Allow authenticated users to insert access for FREE products (gatekeeper auto-grant)
CREATE POLICY "Allow authenticated users to insert access for free products" ON user_product_access
  FOR INSERT
  WITH CHECK (
    auth.uid() = user_id AND
    EXISTS (SELECT 1 FROM products WHERE slug = product_slug AND price = 0)
  );

-- Allow authenticated users full access to user_product_access (admin panel)
CREATE POLICY "Allow authenticated users to manage access" ON user_product_access
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- RLS Policies for audit_logs table
-- Only authenticated users can read audit logs
CREATE POLICY "Allow authenticated users to read audit logs" ON audit_logs
  FOR SELECT
  TO authenticated
  USING (true);

-- Only authenticated users can insert audit logs
CREATE POLICY "Allow authenticated users to insert audit logs" ON audit_logs
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Create function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = timezone('utc'::text, now());
  RETURN NEW;
END;
$$ language plpgsql;

-- Create trigger for products table
CREATE TRIGGER update_products_updated_at
  BEFORE UPDATE ON products
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

COMMIT;
