-- Migration: Update link_display_mode allowed values
-- Description: Change from 'express'|'payment_element' to 'above'|'tab'
--   'above' = Link in PaymentElement wallets section (separate, above tabs)
--   'tab' = Link as a regular tab alongside BLIK/P24/Card in PaymentElement
-- Author: Claude Opus 4.6
-- Date: 2026-02-15

BEGIN;

-- Drop old CHECK constraint (name auto-generated by Postgres)
ALTER TABLE public.payment_method_config
DROP CONSTRAINT IF EXISTS payment_method_config_link_display_mode_check;

-- Migrate existing values
UPDATE public.payment_method_config SET link_display_mode = 'above' WHERE link_display_mode = 'express';
UPDATE public.payment_method_config SET link_display_mode = 'tab' WHERE link_display_mode = 'payment_element';

-- Set new default
ALTER TABLE public.payment_method_config ALTER COLUMN link_display_mode SET DEFAULT 'above';

-- Add new CHECK constraint
ALTER TABLE public.payment_method_config
ADD CONSTRAINT payment_method_config_link_display_mode_check
CHECK (link_display_mode IN ('above', 'tab'));

COMMIT;
