-- Gateflow Project Setup SQL
-- Phase 1, Step 1: Create the `products` Table in Supabase

-- Drop the table if it already exists to ensure a clean setup
DROP TABLE IF EXISTS products CASCADE;

-- Create the products table to store product information
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  icon TEXT,
  price NUMERIC DEFAULT 0 NOT NULL,
  theme TEXT DEFAULT 'dark' NOT NULL,
  layout_template TEXT DEFAULT 'default' NOT NULL, -- New column for layout templates
  stripe_price_id TEXT -- This will hold the ID for the product's price in Stripe
);

-- Comments for your understanding:
-- 1. Enable Row Level Security (RLS) on the new table.
--    This is a critical security step. By default, it denies all access.
--    No one can read, write, or delete data until we create specific policies.
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- 2. Create a read-access policy.
--    This policy allows anyone (a 'public' role) to read ('SELECT') from the products table.
--    This is safe and necessary so our landing page can fetch product details to display them.
CREATE POLICY "Allow public read access for everyone" ON products
  FOR SELECT
  USING (true);

-- 3. Insert some example data so we can test our pages.
--    You can change these values later directly in the Supabase table editor.
INSERT INTO products (name, slug, description, icon, price, theme, stripe_price_id, layout_template)
VALUES
  ('My Awesome Free Product', 'awesome-free-product', 'A fantastic digital goodie, delivered instantly to your inbox.', '🚀', 0, 'dark', NULL, 'default'),
  ('Super Premium Course', 'premium-course', 'Unlock all the secrets with this exclusive, paid course.', '💎', 29.99, 'light', 'price_1Lp9a2J2jY3Z9X8w8b7c6a5', 'default'); -- NOTE: Replace with a real Stripe Price ID later