-- SQL for creating user_product_access table and RLS policies

-- Drop the table if it already exists to ensure a clean setup for testing
-- (Remove this line in production if you want to preserve data)
DROP TABLE IF EXISTS user_product_access CASCADE;

-- Create the user_product_access table to track which user has access to which product
CREATE TABLE user_product_access (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  product_slug TEXT REFERENCES products(slug) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  UNIQUE (user_id, product_slug) -- Ensure a user can only have one access entry per product
);

-- Enable Row Level Security (RLS) on the new table
ALTER TABLE user_product_access ENABLE ROW LEVEL SECURITY;

-- Policy to allow users to read their own access records
CREATE POLICY "Allow users to read their own product access" ON user_product_access
  FOR SELECT
  USING (auth.uid() = user_id);

-- Policy to allow service role to insert access records (used by Edge Functions)
-- This policy allows the 'service_role' (which has admin privileges and bypasses RLS) to insert records.
-- It's safe because the 'service_role' key is secret and used only on the server-side.
CREATE POLICY "Allow service role to insert product access" ON user_product_access
  FOR INSERT
  WITH CHECK (true); 

-- Policy to allow authenticated users to insert access for FREE products
-- This allows client-side insertion for free products, but only for the authenticated user
-- and only if the product's price is 0.
CREATE POLICY "Allow authenticated users to insert access for free products" ON user_product_access
  FOR INSERT
  WITH CHECK (
    auth.uid() = user_id AND
    EXISTS (SELECT 1 FROM products WHERE slug = product_slug AND price = 0)
  );
